<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Apply Discount Code</name>
   <tag></tag>
   <elementGuidId>3c8b0b0a-8a14-45c6-99cb-5cf1b3b85969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//strong[@id='block-discount-heading']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#block-discount-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>5108069e-913b-4467-8b4e-3b1ce6fbdefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>block-discount-heading</value>
      <webElementGuid>be88dcfa-b37d-4cb5-9129-abfaea3c7f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>f1a90e15-d739-45a9-b78e-cfef8f9ed8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>96795c1b-062f-4dac-b275-697d1d4654c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply Discount Code</value>
      <webElementGuid>4f1a3379-d466-4134-9f7b-ffb5be933b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-discount-heading&quot;)</value>
      <webElementGuid>27ecb021-e1a4-4a84-bb45-cdf1992164bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//strong[@id='block-discount-heading']</value>
      <webElementGuid>8f18277e-177e-4066-9515-cdd14cea1898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-discount']/div/strong</value>
      <webElementGuid>86d024dd-9fdc-401e-90e2-47bacc76a719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Shopping Cart'])[1]/following::strong[1]</value>
      <webElementGuid>03dc63ca-fe76-4a4c-96d1-6b5dc0b7d90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Shopping Cart'])[1]/following::strong[1]</value>
      <webElementGuid>9327c390-127c-4ed7-a160-6a1cd26db465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter discount code'])[1]/preceding::strong[1]</value>
      <webElementGuid>3581aec1-6c7e-4cf0-aad3-a80b31035f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Discount'])[1]/preceding::strong[1]</value>
      <webElementGuid>4849c741-8e9b-4c6e-96af-5e72766f1fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply Discount Code']/parent::*</value>
      <webElementGuid>fe3443fd-d404-45b9-8d53-f950232df1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/strong</value>
      <webElementGuid>a7576efb-921a-4f06-a8f1-1ac537a6abc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[@id = 'block-discount-heading' and (text() = 'Apply Discount Code' or . = 'Apply Discount Code')]</value>
      <webElementGuid>c9ed1758-965f-410d-a692-2bce41efee20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
