<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Wayfarer Messenger Bag</name>
   <tag></tag>
   <elementGuidId>13a5db8c-5861-42f4-8631-117142e5c328</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div/div/h1/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.base</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b36783af-bdf3-49e4-b29f-0a39a281e592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base</value>
      <webElementGuid>56aad3c6-3d3f-4d9b-bf11-a43e83ba737b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-id</name>
      <type>Main</type>
      <value>page-title-wrapper</value>
      <webElementGuid>ccc369dc-ba96-454c-a8df-960355e6cf4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>33aaf6fd-c0fa-4616-95f0-36610a0683d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wayfarer Messenger Bag</value>
      <webElementGuid>347cb33f-8485-4f04-b854-8e4ad3d1f74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;product-info-main&quot;]/div[@class=&quot;page-title-wrapper product&quot;]/h1[@class=&quot;page-title&quot;]/span[@class=&quot;base&quot;]</value>
      <webElementGuid>6a2fe83f-b8bb-4dfe-9abf-80d729ebd9f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div/div/h1/span</value>
      <webElementGuid>0c8047c7-54a3-426b-a4e2-70ec79c4c8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wayfarer Messenger Bag'])[2]/following::span[1]</value>
      <webElementGuid>6bdbad0e-3eb9-4efb-b5d2-148f112bef9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating:'])[1]/preceding::span[1]</value>
      <webElementGuid>5b804767-5a77-4417-83ab-86f1de74697b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>8d71d48e-7bbd-422d-ac24-f4c54ac03c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Wayfarer Messenger Bag' or . = 'Wayfarer Messenger Bag')]</value>
      <webElementGuid>8743700f-f8a9-4ef4-9043-4c053a9c24de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
