<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Check  Money order_billing-address-sa_4ac8d0</name>
   <tag></tag>
   <elementGuidId>141a230f-9742-4ed6-9aa3-6a3ba1104333</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing-address-same-as-shipping-checkmo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing-address-same-as-shipping-checkmo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46d4516f-3244-4a9f-8334-aabbad8890a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e3a76fae-b0f1-43cb-b60a-13c677a1617a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing-address-same-as-shipping</value>
      <webElementGuid>551747b0-5d9c-431b-9a72-743e4143c526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>checked: isAddressSameAsShipping, click: useShippingAddress, attr: {id: 'billing-address-same-as-shipping-' + getCode($parent)}</value>
      <webElementGuid>99b9b58b-d7d1-4889-8178-1c0df43fa509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing-address-same-as-shipping-checkmo</value>
      <webElementGuid>47118d9e-2212-4979-b461-c930a901751f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing-address-same-as-shipping-checkmo&quot;)</value>
      <webElementGuid>d4d08b8f-f15f-4928-ba21-6ef3fa2863a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing-address-same-as-shipping-checkmo']</value>
      <webElementGuid>7a4b3c16-36b2-44c8-ad2a-372920a80cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-method-load']/div/div/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>031357f6-437c-4549-85ed-72df35071a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>f3eb4431-7b72-4a04-a2c7-507c83d41424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'billing-address-same-as-shipping' and @id = 'billing-address-same-as-shipping-checkmo']</value>
      <webElementGuid>d96f1d51-83cb-49dd-8281-59029dcca572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
