<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Fixed</name>
   <tag></tag>
   <elementGuidId>bed5f450-5f55-4244-839b-c8c8a105c509</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='label_method_flatrate_flatrate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#label_method_flatrate_flatrate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>338bd858-12d8-40e6-a0d6-95c987760d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col col-method</value>
      <webElementGuid>119c0c3d-15c6-4112-93ff-781d2e214d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {'id': 'label_method_' + method.method_code + '_' + method.carrier_code}, text: method.method_title</value>
      <webElementGuid>ac481f2a-1f2b-43c1-aa49-c7cb24b00d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>label_method_flatrate_flatrate</value>
      <webElementGuid>7c525f85-022a-4bec-bc3c-a37eff9ca542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fixed</value>
      <webElementGuid>fdf6a792-352c-4c1c-9c80-c7e270b2fcc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label_method_flatrate_flatrate&quot;)</value>
      <webElementGuid>a2faf273-5082-424a-bf9f-7d02ff754b1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='label_method_flatrate_flatrate']</value>
      <webElementGuid>c7bf8346-60be-47b9-8ca7-94c6e6ec4ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-method-load']/table/tbody/tr[2]/td[3]</value>
      <webElementGuid>58c37608-4ee9-4cec-9c88-e06cdadbeb5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$20.00'])[1]/following::td[1]</value>
      <webElementGuid>6c584517-3e3a-4f0d-a0fd-aa679e66c744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best Way'])[1]/following::td[3]</value>
      <webElementGuid>dc55c012-af81-4e1e-9756-e7a0a97a627b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flat Rate'])[1]/preceding::td[1]</value>
      <webElementGuid>1ce7ef05-7b10-4517-b6c1-264dccffd661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::td[2]</value>
      <webElementGuid>00bf2056-9183-4f11-a71e-5353f463d11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fixed']/parent::*</value>
      <webElementGuid>91c655b9-9711-4caf-a67c-e2b676c8ea20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]</value>
      <webElementGuid>d530454d-e3c4-4949-a469-bd3d60eb4160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'label_method_flatrate_flatrate' and (text() = 'Fixed' or . = 'Fixed')]</value>
      <webElementGuid>f823d61d-d531-4fc5-8a3c-9f146acebce9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
