<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ad_ad_iframe</name>
   <tag></tag>
   <elementGuidId>66b1be74-4d96-469e-97b8-0648268eb86b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ad_iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ad_iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8869bd7f-33ee-4615-9c4e-7550768fe5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>686d8408-d993-4244-956c-09ef2abd5658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ad_iframe</value>
      <webElementGuid>d7b1a1fa-b2a9-4751-9e8f-73e3023ef5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ad_iframe</value>
      <webElementGuid>00efd64f-7ff0-429c-8a6b-ccdeaac7145c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8cd265be-0e37-4835-ae42-f20b2864b1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>d90b32fa-06cf-4804-af4f-526a3ef60020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>46ab5929-8461-46a7-8f8f-ff22f575bf84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>415px</value>
      <webElementGuid>f8e8c1ca-fa7d-44ee-bf0a-c3f7e7c73b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>166px</value>
      <webElementGuid>3d4c8cb1-9882-4ca2-ab0e-8dde069445d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ad_iframe&quot;)</value>
      <webElementGuid>c190e789-d7cb-47cf-9ae8-897ed157a353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Shopping Cart/Page_Home Page/iframe_Forgot Your Password_aswift_6</value>
      <webElementGuid>397e50a6-cd77-4d71-a288-519a87e81c30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ad_iframe']</value>
      <webElementGuid>d2a225e9-3260-445d-b2c1-b77967ebdc23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='creative']/iframe</value>
      <webElementGuid>43cb9a01-3dad-4283-9d14-60ee01dbf5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f510b0ab-cc3f-4e93-9c2e-0c2b896f8c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Advertisement' and @id = 'ad_iframe' and @name = 'ad_iframe' and @src = 'about:blank']</value>
      <webElementGuid>773b2460-ef09-42dd-8e85-89292a2d89cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
