<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Forgot Your Password_aswift_6</name>
   <tag></tag>
   <elementGuidId>7ab576f0-9abd-4db8-a504-20fc6785a8bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='aswift_6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aswift_6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>942c17d1-7400-4423-bf3f-be6ad4c4afb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aswift_6</value>
      <webElementGuid>2b442827-e4f5-43de-8195-b81bafb5dec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aswift_6</value>
      <webElementGuid>4c32fc48-b33d-464d-9dd3-e28b32c7fb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation</value>
      <webElementGuid>8206f21c-22c7-4035-bc94-ec263d39780e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1051e5c1-963a-4912-988b-4f07fd5467cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5413d560-7298-431d-9e66-c87251835b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>95103411-86f8-4642-b776-9234d26400a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>92d1db8d-8068-480a-bf55-e2e1efa2921f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1a2e24bf-484f-4b7f-bc1c-ccbd81df1444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>288c3595-91e9-48ed-ae0c-670f5abe7aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f9229d90-d1be-4503-a57f-b6ffeaee2081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://googleads.g.doubleclick.net/pagead/html/r20250617/r20190131/zrt_lookup_fy2021.html#RS-0-&amp;adk=1812271808&amp;client=ca-pub-7399332034053978&amp;fa=8&amp;ifi=7&amp;uci=a!7</value>
      <webElementGuid>f1654000-ae5d-44ba-935c-5f5a37f8938d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-container-id</name>
      <type>Main</type>
      <value>a!7</value>
      <webElementGuid>536e92f0-d4de-49c9-bd79-fbf0e695ca0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fc0a2e33-c3b1-4c41-9117-d1f5f0acafb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>196ed9a6-4790-4599-b108-7b77876aab27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>37e2f1c0-bc6e-4ebd-b04a-fc3a10f44941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-query-id</name>
      <type>Main</type>
      <value>CJXC4bigjI4DFYab2AUdLmgF7A</value>
      <webElementGuid>7ed2ed5d-ca84-402f-a9fd-dca8ce4606d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-load-complete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b135f04e-2601-4a57-993c-e2ff937fc344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aswift_6&quot;)</value>
      <webElementGuid>2cf5535b-bcc2-415e-b93e-3ec30869af15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='aswift_6']</value>
      <webElementGuid>a58860e8-d343-4187-bdbe-adb2f3adb364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aswift_6_host']/iframe</value>
      <webElementGuid>b98f3bcc-6377-4ad5-879d-dccb74d2cf8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//html/ins/div/iframe</value>
      <webElementGuid>c3f2c237-5c05-426c-80a3-ec6e2515ca07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'aswift_6' and @name = 'aswift_6' and @src = 'https://googleads.g.doubleclick.net/pagead/html/r20250617/r20190131/zrt_lookup_fy2021.html#RS-0-&amp;adk=1812271808&amp;client=ca-pub-7399332034053978&amp;fa=8&amp;ifi=7&amp;uci=a!7' and @title = 'Advertisement']</value>
      <webElementGuid>4264b3ac-94b7-4fbb-8040-40c269c78114</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
